### ISSUE TITLE
0.0.2 release

### ISSUE THREAD

**Issue by visualphoenix** [y-ken/fluent-plugin-sentry#4]
After we make #3 suitable for commit, it would be nice if you could publish a new gem.

Thoughts?

**Comment by y-ken** [comment]
It coming fluent-plugin-sentry v.0.0.2 today!
https://rubygems.org/gems/fluent-plugin-sentry

**Comment by visualphoenix** [comment]
:star: :star2: :star:

**Comment by y-ken** [comment]
If it could, It is very happy to write blog article with these topics.

* sentry use case
* Fluentd helps to improve stability on sentry high load
* how to integrate with fluentd

**Comment by visualphoenix** [comment]
sure. i'm working on a demo which will be perfect for a blog post about fluentd and sentry. i have some questions about fluent-plugin-rewrite-tag-filter i will ask about in an issue on that project.

**Comment by visualphoenix** [comment]
nevermind figured it out. thanks again for writing this plugin!

**Comment by y-ken** [comment]
Sounds great. Thank you very much for hear that.
It's ok to ask me fluent-plugin-rewrite-tag-filter too.
